name: membrane
channels:
  - conda-forge
dependencies:
  - numpy <=1.24
  - scipy
  - numba
  - matplotlib
  - libMobility
  - pyamg
  - pyvista
  - cmocean
  - pip
  - pip:
      - git+https://github.com/brennansprinkle/Rigid_Body_Light@dev_python_interface