name: membrane
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy <=1.24
  - scipy
  - numba
  - matplotlib
  - pyvista
  # - scikit-umfpack
  # - StochasticHydroTools::libMobility
  - pyamg